spring:
  jackson:
    default-property-inclusion: non_null

si:
  base-path: https://mtf.api.identity.mastercard.com/mtf/3ds/miserver/requestor
  logging:
    pattern:
      console: '%d{HH:mm:ss.SSS} [%level] %msg%n'

  auth:
    keyStore:
    keyStore-password:
    keyStore-type:

app:
  encryption:
    cert:
    enabled: false